version: '3.7'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.db-data:/var/lib/postgresql/data
  redis:
    image: "redis:4.0.14-alpine"
    command: redis-server
    ports:
     - 6379:6379
